[global]
description = "ノミナルケース"
max_timestep = 200

[visualization]
interval = 0

[movie]
dpi = 200
interval = 50

[model]
population = 100
width = 100
height = 100
speed = 1
vision = 5
separation = 2
motality = 0.1
infection_rate = 0.3
cohere = 0.025
separate = 0.25
match = 0.04

